# Generated by Django 2.2.3 on 2019-08-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190726_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('MX', 'Mexico'), ('US', 'United States'), ('CL', 'Colombia'), ('VZ', 'Venezuela'), ('AR', 'Argentina'), ('BR', 'Brazil')], default='MX', max_length=2),
        ),
    ]
